config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root 'home#index'
  get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except:[:index, :show]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :age, :email, :phone)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend, local: true) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :age %>
    <%= form.number_field :age, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class:"form-control" %>
  </div>

  <div class="actions mt-3">
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<h1 class = "text-center mb-3">Friends List</h1>

<table class="table table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Age</th>
      <th>Email</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.first_name %></td>
        <td><%= friend.last_name %></td>
        <td><%= friend.age %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= link_to 'Show', friend, class:"btn btn-info btn-sm" %></td>
        <td><%= link_to 'Edit', edit_friend_path(friend), class:"btn btn-warning btn-sm" %></td>
        <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
<div class="text-center">
  <%= link_to 'Add New Friend', new_friend_path, class:"btn btn-success text-center" %>
</div>
<%end%>

app/views/friends/new.html.erb
<h1 class="text-center mt-3">Add New Friend</h1>

<%= render 'form', friend: @friend %>
<br>
<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<div class="card text-center mt-5 dark">
  <div class="card-header">
    <h5 class="card-title">  
      <%= @friend.first_name %>
      <%= @friend.last_name %>
    </h5>
  </div>
  <div class="card-body">
    <p class="card-text">
      <strong>Age:</strong>
      <%= @friend.age %> |

      <strong>Email:</strong>
      <%= @friend.email %> |
      
      <strong>Phone:</strong>
      <%= @friend.phone %>
    </p>
    <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-warning btn-sm" %>
    <%= link_to 'Back', friends_path, class:"btn btn-info btn-sm" %>
    <%= link_to 'Destroy', @friends, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-sm" %>
  </div>

  <div class="card-footer text-muted">
    2 days ago
  </div>
</div>

app/views/home/_footer.html.erb
<footer>
  <div class="container">
    <div class="text-center"><i class="fas fa-ellipsis-h"></i></div>
    
    <div class="row text-center">
      <div class="col-md-4 box">
        <span class="copyright quick-links">Copyright &copy; Shaharyar Ahmed
        </span>
      </div>
      <div class="col-md-4 box">
        <ul class="list-inline social-buttons">
          <li class="list-inline-item">
            <a href="#">
            <i class="fab fa-twitter"></i>
          </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
            <i class="fab fa-facebook-f"></i>
          </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
            <i class="fab fa-linkedin-in"></i>
          </a>
          </li>
        </ul>
      </div>
      <div class="col-md-4 box">
        <ul class="list-inline quick-links">
          <li class="list-inline-item">
            <a href="#">Privacy Policy</a>
          </li>
          <li class="list-inline-item">
            <a href="#">Terms of Use</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
      <%= link_to "Friend App", root_path, class: "navbar_brand text-light text-decoration-none"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Friends", friends_path, class:"nav-link ms-3" %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Add Friend", new_friend_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
          </li>
        <% end %>

        <li class="nav-item">
            <%= link_to "About Us", home_about_path, class:"nav-link" %>
          </li>

      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Page</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Home index page hereeee</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Friends</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'home/header'%>

    <div class="container">
      <br>
      
      <% if notice%>
        <%= render 'layouts/alerts'%>
      <% end %>

      <%= yield %>
    </div>

    <%= render 'home/footer'%>
  </body>
</html>